# Generated by Django 4.2.6 on 2023-11-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0002_alter_blog_slug_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_blogs', to='Blog_app.category'),
        ),
    ]
